drop table if exists home;
drop table if exists images;

create table home(
homeid serial primary key,
home_name text,
price integer,
max_guests integer,
describe_main text, 
describe_space text,
describe_guest_access text,
describe_interaction_with_guests text,
describe_other_things_to_note text,
address text,
city text,
host_id int,
FOREIGN KEY (host_id) REFERENCES users(user_id)
);

insert into home
(home_name, price, max_guests, describe_main, describe_space, describe_guest_access, describe_interaction_with_guests, describe_other_things_to_note, address, city, host_id)
values
('Modern Home in Uptown Phoenix', 73, 3, 
'A remodeled mid-century modern condo with character: fresh, comfortable with everything to make your stay pleasant. 2 real queen beds, quality towels, luxury linens. The entire condo is yours. Near many awesome local restaurants.

Central location near the airport (8.2 miles / 15 min.), downtown Phoenix, Scottsdale, Convention Center (8 miles / 15 min.), Sports parks: all easily and quickly accessible.

More information
Close to many hiking trails in the Phoenix Mountains and Camelback Mountain and restaurants.',
'This modern condo is completely remodeled offering all the amenities you may want or need for a comfortable stay - no matter how long with a central location near popular places like the airport, convention center, and sports arenas or hiking and lots of restaurants.

Watch Netflix and cable (Sling) via Roku - should be all logged in already, fast Wi-Fi internet, full kitchen + equipment (toaster oven - no microwave - the food is really better when it''s not nuked, washer and dryer. It''s all updated, yet the building retains many of it''s mid-century modern features: like the beautiful adobe brick wall, post and beam architecture and some of the well-done tile work.

With a comfortable queen bed in each bedroom, there is ample room for up to four people. Pretty much all that you''ll need is provided: towels, soaps, shampoo and even a hair dryer and clothes iron.

Tea and coffee for the french press are provided. The frig. has some basic condiments like ketchup, sriracha, mustard plus basic spices plus a bottled water and usually a few bottles of beer.

This is our second condo. Our other one has great reviews from guests. When preparing this one for you, we aimed to meet and exceed the comfort of the other condo. Our goal is to make that kind of place we would enjoy staying in and returning to.

The condo is about 950 square feet - third party measurement.

This is a small community of only four condos that share a large green yard with a sitting area in the middle where you can enjoy the weather, read a book, have coffee or just lounge around.

If you''re here in the winter it may be just in time to have an orange or tangelo from one of the citrus trees.

The entire place is yours. The condo is completely stocked so you can be the chef if you want, make coffee in the French press or just warm up that take out.

Access to the condo is through a lockbox. This is easy to use and allows you to get in whenever you arrive, but, if you want, we''ll be happy to meet you: it''s your choice.',
'You can use pretty much everything in the condo, it''s there to make your stay comfortable.

The kitchen has utensils, plates, cups, glasses and a set of pots and pans: get creative or just warm up food in the oven or toaster oven.

Extra linens and toiletries are in the hall closet. Anything in the frig. is there for your use.

The laundry is just outside in the grey laundry room by the front door - access it with the sa
me key as the entry doors.',
'Access to the condo is through a lockbox. This will allow you to get in no matter what time you''ll arrive. It''s easy to use and convenient, though we''re near by if you would like to meet. It''s your choice.',
'The sitting area in the middle of the two building is for common use. The citrus is usually good from early December until about April or May - you''re welcome to have some.

Third Sleeping Area - on couch in living room - if needed.

Sleeping arrangement in the living room. An additional person may sleep on the sofa. It is very comfortable for someone up to about 5 foot 9 inches tall. The large pillows come off and it''s like a twin bed (73 long by 33 wide).

FYI: We wash ALL bedding - ALL OF IT - every single time - even the comforter cover(s) - WITHOUT EXCEPTION. This is what we would expect and that is what we provide. I take pride in cleanliness - it is no. 1 on my list.',
'1327 W Woodland Ave
Phoenix, AZ 85007',
'Phoenix',1),
('Charming Coronado Guest House', 67, 2, 
'Welcome to Phoenix and the Charming Coronado Guest House. We are centrally located within minutes of Downtown Phoenix and only a short drive to Sky Harbor Airport.',
'The most 5 star reviews in Phoenix! No cleaning fees and no security deposit. Those are silly.
The guest house has a keypad for entry so no need for key exchange and check-in anytime after 2pm.

The Coronado Guest House is located behind our historic 1937 home and is located in the heart of the Coronado Historic Neighborhood. We are within walking distance to many great restaurants and downtown Phoenix is only a 5 minute drive away. Downtown Phoenix is home to numerous sporting venues such as Chase Field and US Airways Center, as well as the Phoenix Art Museum, Arizona Science Center, Heard Museum, and the Children''s Museum. Many great restaurants are within a 5 minute walk and we can recommend a few of our favorites for you. The 7th St. and Oak bus stop is only a 5 minute walk. We are also only a 10-15 minute walk to the Oak Metro Light Rail station which can take you to Downtown Phoenix, Phoenix Sky Harbor Airport, Tempe with its eclectic Mill Avenue and home to Arizona State University, and Mesa with it''s wonderful Mesa Center for the Arts.

Your private guest house has a queen bed. You have a 32 inch flatscreen TV with DirectTV satellite as well as 300 Mbps wireless internet throughout the entire backyard. The french doors open up to a gazebo perfect for outdoor dining and seating for 8. Lounge on the patio in the hammock. There are also screen doors that you can lock so you can leave the inside doors open at night and enjoy the cool air. The guest house has a full kitchen and bathroom. Laundry is available in our main house if needed. The guest house entrance is through our driveway gate and is separate from our main house.

We have 3 chickens that provide us with fresh eggs daily and you are welcome to as many eggs as you would like.

Yoga studios nearby:
SuTRA Midtown Yoga - 3 minute walk
Yoga Phoenix (Kundalini Yoga) - 30 second walk

Nearby Restaurants: (3-10 minute walk)
Main Ingredient
Humble Pie
Wy-Not Cafe
Nami & Green
America''s Taco Shop
Coronado Cafe
McAplines Soda Fountain
Rice Paper
Tuck Shop
Astor House

Day trips from Phoenix include:
Sedona - 2hrs. 
Jerome - 2 hrs. 
Tucson - 2 hrs.
Prescott - 2 hrs.

It''s hard to do the Grand Canyon as a day trip and really enjoy your time there. Instead fly into Phoenix and spend 1 or 2 nights here then spend a night in Flagstaff or at canyon itself. 4 1/2 hr drive from Phoenix.',
'Laundry facilities, backyard, fire pit, outside dining.',
'I''m usually always around as I work from home so chances are I''ll be here to show you around - unless I''m traveling the world. In that case just call me if you need anything.',
'Wow that''s a lot of yellow stars.',
'1036 E Monte Vista Rd Phoenix, Arizona',
'Phoenix',1),
('South Phoenix Casita with Saltwater Pool', 50, 2,
'Our casita is detached from our home and is located in a private gated community in the foothills of South Mountain, about 15 minutes from downtown phoenix. The casita has a private entrance with all of the comforts of a hotel room. There is a smart tv with netflix and HBO Go and basic cable. There is a Mini fridge and Keurig. Access to our private salt water pool with mountain views.',
'300 sqft casita that is located in the front of our home. The casita is detached from our home with a private entrance. You will also have your own heat and A/C unit with nest thermostat. There is a tile bathroom stocked with soap, shampoo and conditioner.',
'Guests will have access to our private pool with mountain views. There are nice lounge chairs to relax in the sun or under the stars. Please do not invite anyone over to use the pool. There is a courtyard outside of the casita that you are welcome to use as well.',
'We typically stay out of the way of our guests, however we live in the main house of the property and are usually available to help with anything!',
'The pool is not heated but typically very warm May-September.', 
'1830 W Telegraph Pass Rd
Phoenix, AZ 85041',
'Phoenix', 1),
('Green Gables Guest House', 69, 2, 
'Awaiting your stay a beautifully remodeled guest house in the historic Green Gables District. This beautifully restored Guest House features one bedroom, one bath, newly redesigned and fully functional kitchen. 2 Queen size beds on simply the most comfortable memory foam mattress for those nights when the day’s activities leave you yearning for a peaceful night’s rest.',
'Completely remodeled 1 bedroom 1 bathroom contemporary guest house with brand new stainless steel appliances and a queen size sofa sleeper with pressure sensing mattress, TVs in both the living room and bedroom.. This cozy cottage boast 640 square feet perfect for those groups traveling with 4 people. The bedroom has a 45 inch TV with a queen size bed and pressure sensing foam mattress. The yard is completely fenced for privacy and security with plenty of space to relax and enjoy the beautiful fall, winter, and spring seasons here in Phoenix.',
'Guests will have access to streaming TV services such as Netflix and Amazon all of the streaming media which are available through Roku. including high-speed internet and your own private patio. Guesthouse features a private yard fenced for safety and security, there is also access to a washer and dryer located in the main house.',
'When you arrive, Dan or Kevin will be there to greet you and welcome you home :-) Should you require anything during your stay your hosts are only a few feet away and will be available your through out your stay. So please let them know how the can help.',
'Enjoy our pool :) It is not heated but typically very warm May-September.',
'2502 N Foote Dr Phoenix AZ 85002', 'Phoenix', 1),
('Stylish Sanctuary with Pool/Spa in Downtown Phx.', 58, 5,
'Charming home in a quiet location near Downtown Phoenix. Nestled in the heart of the quaint FQ Story Historic District. This home combines historic charm with mid-century modern character.

Sky Harbor - 5.4 miles
Convention Center - 1.6 miles
Talking Stick Arena - 1.8 miles
Chase Field - 2 miles',
'This beautiful 3 bedroom home offers all of the amenities you may want or need for a comfortable stay. Near popular places like Phoenix Sky Harbor Airport, Convention Center, sports arenas and tons of restaurants/entertainment. It is close proximity to fantastic food, live music, public transportation, and exciting city events, which makes this an ideal location to be introduced to a side of Phoenix that even some locals aren''t aware of.

Hang by the pool and catch some rays in the back yard, unwind in the heated spa after a long day or during our colder months, and enjoy the covered patio with classic twinkle lights and outdoor seating creating a warm and welcoming vibe.

Watch Netflix, Hulu and more via Roku Smart TV. We have fast Wi-Fi internet. A full kitchen with cooking equipment, plates, bowls, glasses, utensils, toaster oven, microwave and coffee maker. Washer and dryer available for guest use. Tea and coffee are provided. The refrigerator has a Brita.

With queen beds in two of the bedrooms, and a futon in the third bedroom, there is ample room for up to 5 people (2 people on each queen bed and 1 person on the futon). All of the essentials are included: towels, soaps, shampoo, hair dryer. There is unfortunately no outlet in the bathroom due to the home being historic.',
'Guests have access to the entire home. The front yard has plenty of room for parking in the driveway or free street parking. Guests also can enjoy the back yard with covered patio and pool/spa.

The only part of the property guests do not have access to is a detached guest house/garage that is occupied 3 - 4 months of the year. They have their own private patio, they do not use back yard/pool/spa.',
'Access to the home is through E Lock. This will allow you to get in no matter what time you arrive. It is easy to use, convenient and safe since you will have your own custom key code.

We are constantly available for any of our guest needs. We are best reached by sending us a message on the Airbnb App for feel free to give us a call. We also live close by the property, so we can stop by quickly if needed.',
'There is a hot tub and pool open for guests.',
'745 W Fillmore St, Phoenix, Arizona 85007', 'Phoenix', 1);

create table images (
img_id serial primary key,
img_url text,
home_Id int,
main_Image text,
FOREIGN KEY (home_Id) REFERENCES home(homeid)
)

insert into images 
(img_url, home_id)
values
('https://a0.muscache.com/4ea/air/v2/pictures/54af8626-fbee-43a3-b13b-dda795b80209.jpg?t=r:w2500-h1500-sfit,e:fjpg-c90', 1, 'true'),
('https://a0.muscache.com/4ea/air/v2/pictures/a73e694b-544e-483c-bcf8-7443dbdd824a.jpg?t=r:w2500-h1500-sfit,e:fjpg-c90', 1),
('https://a0.muscache.com/4ea/air/v2/pictures/29f509a7-491f-4404-8dd7-db3dac06aef4.jpg?t=r:w2500-h1500-sfit,e:fjpg-c90', 1),
('https://a0.muscache.com/4ea/air/v2/pictures/c4aa5cae-c1e9-4aea-85a4-aff756fdbdb7.jpg?t=r:w2500-h1500-sfit,e:fjpg-c90', 1),
('https://a0.muscache.com/4ea/air/v2/pictures/cee7205c-ca78-4aac-8802-1844b31c45de.jpg?t=r:w2500-h1500-sfit,e:fjpg-c90', 1),
('https://a0.muscache.com/4ea/air/v2/pictures/59ac9679-11a6-4d57-ad45-aa74a0b0aab4.jpg?t=r:w2500-h1500-sfit,e:fjpg-c90', 1),
('https://a0.muscache.com/4ea/air/v2/pictures/1d84dc9b-6f58-41f7-8cd9-e58dbed02523.jpg?t=r:w2500-h1500-sfit,e:fjpg-c90', 1);
('https://a0.muscache.com/im/pictures/5fd7bfb3-2ad3-447c-bcd9-a5248159bfde.jpg?aki_policy=xx_large', 2, 'true'),
('https://a0.muscache.com/im/pictures/296daf07-e291-4b64-91a5-6b6a3a8ac0bc.jpg?aki_policy=xx_large', 3, 'true'),
('https://a0.muscache.com/im/pictures/bb0a685a-a362-45e6-aead-944576ee8f80.jpg?aki_policy=xx_large', 4, 'true'),
('https://a0.muscache.com/im/pictures/66ac7ea1-9fb0-49dd-80e1-ebd9ed4a3980.jpg?aki_policy=xx_large', 5, 'true');

-- Aisha's insert statements into home table (cities: Williams, Tucson, Cottonwood)
insert into home
(home_name, price, max_guests, describe_main, describe_space, describe_guest_access, describe_interaction_with_guests, describe_other_things_to_note, address, city, host_id)
values
--Tucson 
('Private Southwestern Style Casita', 59, 4, 'May - August $59 - 89 nightly. Otherwise Rates are Seasonal. This 1940''s property is Centrally Located just 2.5 miles from the U of A in the Peter Howell neighborhood. The casita Comes with Complete Kitchenette, Central AC/Heat, Queen Sized Bed, Sofa Bed, Table For 4, Fridge, Free Wifi, Cable Tv, Off Street Parking, Pots Pans, Iron, Microwave, Toaster, Beach Cruisers, and a well maintained private backyard! And wonderful hosts. :) , and Lots of good eating close by!!','This Private Southwestern Casita comes with complete kitchenette, new bathroom, Large room with Queen Bed, Living/Bedroom with a New Sofa Bed for extra Guests or Relaxation Time, as well as Dining Room Table with Setting for 4. The Guest Casita just oozes with charm & is split up into two spaces ( both sides yours of course to use !!The casita is well equipped with everything you could possibly need for a long or short stay in Tucson! Amenities: This Casita is Fully Solar - with Central A/C and Heat, kitchenette, Refrigerator, Free Wifi, washer, dryer ( clothes line too ), iron & ironing board, pots and pans, sheets & towels, silverware, blender, toaster, microwave, and Beach Cruisers. We are just Blocks from some great restaurants (Zaynas, Feast, Kazoku), groceries (Whole Foods and Sprouts), cinemas (El Con and Loft) shopping (Target, El Con Mall, CVS), and parks (Alvernon neighborhood park, Reid Park, Reid Park Zoo (like a mini San Diego Zoo!), Randolph Tennis and Golf Center) and the Tucson Botanical Gardens. You will love the serenity, the classic charm, and the convenience. Call with Any Question or Special Requests. Taylor & Yuko', 'During your stay, you will have access to the Casita through the private driveway, where there is a designated space for your vehicle. Fully fenced back yard , BBQ grill , bikes and more', 'We live in the neighborhood also and are available ANYTIME for questions. That being said, we enjoy privacy when we travel, so unless you reach out to us with questions, we will happily leave you in peace to enjoy your stay. If you need us, we''re happy to share our knowledge of the neighborhood and help you find whatever you need in Tucson.', 'If you have a chance, take a walk around the Peter Howell neighborhood we are a part of and enjoy all the beautiful homes. (It is a very lovely neighborhood). If this property is unavailable or your looking for something bigger for similar price be sure to look up our other property : " La Casita Bonita ", or " Quaint Casita in Heart of Tucson ", or " Central Tucson Midtown Charmer ". All of them are in the same neighborhood within Blocks of one another.', '802 W Calle Adelanto Tucson, AZ 85705', 'Tucson', 1);
('Tucson Poet''s Studio',95 , 4, 'As featured in New York Magazine, June 19, 2015 "Taste the Flavors of Tucson" *NEW* lovely queen size bed since 11-2015 with Saatva Flagship Luxury Firm mattress set-true comfort!', 'The Poet''s Studio is a peaceful retreat in the heart of Tucson. The studio shares the private, walled 1/3 acre lot, courtyard and pool with two other structures: a second, working studio and the original mud-adobe home built in the 1940s. The studio is crafted in the classic Santa Fe style, built of sun-dried adobe with a corner beehive fireplace. You will have private views out both windows, with a mountain view to the north and a view overlooking the pool to the east. The unheated "Plunge Pool" is just swimmable (4-1/2 feet deep) and reaches temperatures in the 80s during the summer. The studio boasts a lovely queen-sized bed with a Saatva Flagship Luxury Firm mattress set, a 3/4 bath with a walk-in spa shower and a modern, well-appointed kitchenette. Additional amenities include air conditioning and heating, high speed wireless internet, iHome radio for your iPhone, wireless capable flat screen TV (use your NetFlix account!) with Direct-TV., professional induction hotplate, Kuerig coffee maker, toaster oven, microwave, Cuisinart gas BBQ and solar panels.  The space is well-equipped. Upon your arrival, you will find coffee, Tucson Tamale Company green corn tamales, granola bars, fruit and chocolate to get you started. I also provide drinking water from Aqua Vita (distilled, magnetically treated) given the tap water is chlorinated and quite mineral-rich. Soaps, dishes, pots and pans, pool towels, robes, hair dryer, iron... I have tried to think of everything, but if you find you are missing something, I have an entire house full of stuff next door - just ask!', 'During your stay, you will access the studio through a private side yard. A covered car port is dedicated for your vehicle.', 'We are happy to personally interact with guests. We provide our contact and personal cell numbers as well.', 'We are within 2 miles of great restaurants (Zaynas, Feast, Kazoku, Lodge on the Desert), groceries (Whole Foods and Sprouts), cinemas (El Con and Loft) shopping (Target, El Con Mall, CVS),and parks (Alvernon neighborhood park, Reid Park, Reid Park Zoo (like a mini San Diego Zoo!), Randolph Tennis and Golf Center) and the Tucson Botanical Gardens. You will love the serenity, the classic charm, and the convenience. ', '1003 N Perry Ave Tucson, AZ 85705', 'Tucson', 1);
('Private Desert Casita with Pool', 79, 3, 'The Private Desert Casita is located on 3 beautiful acres east of Tucson that includes a pool. As the name indicates the Casita is separate from the main house and has its own entrance. We are approximately 1 mile from Saguaro National Park East. Self check-in via keyless entry. Door code provided prior to your stay.', 'The room has a king bed and a futon that pulls out to a bed. Please note that this is a studio so the king bed and futon are in the same room. The casita also has a microwave, hot plate, mini-fridge, sink, coffee maker, ceiling fan, bathroom with shower and large closet. The views of the surrounding desert and mountains are spectacular.', 'Private entrance detached studio guest house in Tucson 1 mile from Saguaro National Park East. Guesthouse is located behind main house and next to the swimming pool (not heated) .', 'We are always available to reschedule check in times as needed. Please let us know and we will accomodate.', 'Well behaved Pets are always welcome.', '724 W Calle Matus Tucson, AZ 85705', 'Tucson', 1);
('Catalina Foothills Estate Guest Studio Wing',60 , 4, 'Welcome to Casita Tolsa!  We are close to La Encantada Mall with Shopping, and Restaurants close by. Our Studio Guest Suite has private entrance, parking, outdoor BBQ, Patio Dining, Private Roof Deck, mini fridge, coffee Machine, toaster oven and microwave. Local Art Galleries close by with views of every mountain range and the city. Enjoy the traditional territorial style, the wood beam ceilings, the patio, the fireplace. ', 'Our Guest Suite is separated from the main house by a locked door and hallway, it is very private. The suite has a mini fridge, Keurig coffee machine, toaster oven and microwave. Includes 55" HDTV with HBO, Netflix, Hulu, Amazon and many new popular movies. The Guest wing has its own roof deck and large patio including an outdoor grill, with great views of the city and mountains surrounding Tucson. We are a quick 15min drive to U of A campus and downtown. ', 'Our Studio Guest Suite has private entrance and parking, outdoor BBQ, Patio Dining, and Private Roof Deck.', 'The main house where we live is separated by a locked door. We''ll be happy to point you in the right direction and give you tips on the best to do, see and eat in town.', 'HDTV with Netflix, Hulu, HBO, Amazon Video Roku and High speed wireless Internet', '1747 N Palo Verde Blvd Tucson, AZ 85716', 'Tucson', 1);
('5-acre Cowboy Hideaway with Mini-Donkeys & Horse!', 119, 2, 'CASITA DEL REY is a charming, private 2-room, 560-sq foot cowboy guesthouse on a stunning 5-acre estate, including a first-class equine therapy facility for horses and the rescue of donkeys in the SW U.S. We have it all...charm, nature and comfort! A gorgeous pool, sunset patios & chance to get up-close to horses and donkeys! Amenities: kitchenette, refrig, stove top, steam shower, basketball court, picnic area, labyrinth, walking paths, high-speed WiFi/HDTV, shopping/dining w/in 5 minutes!', 'Southwestern casita on 5 acres. A true oasis in the heart of Tucson! The interior is both charming and unique. Inside-cozy up by the gas stove fire or relax in the steam shower. Outside, feel free to bask in the sun or shade, go for a swim, tour the grounds, play basketball, picnic or hammock and view the spectacular sunsets and wildlife. To mark the end of each day and to honor the servicemen and women who’ve made the ultimate sacrifice in defense of our freedoms, a 58-second Taps bugle call will sound on the Casita Del Rey grounds every night at Civil Dusk (approximately 25 minutes after official sunset) and at High Noon on both Memorial Day and Veterans Day. Also on the Casita Del Rey estate resides the first-class El Dorado Stables for The Oracle Institute, the home to equine therapy horses and the rescue of donkeys from throughout the SW United States. Book now and be able to enjoy these beautiful animals!', 'Guests have access the estate property. The pool (unheated) is located behind the fenced area around the main house. Do be sure to close and secure the gates at all times. This keeps unwanted wildlife from getting into the yard. Thank you!', 'The owners live on-site.', 'One or both owners will assist with any questions or needs during your stay.', '3660 E Fairmount St Tucson, AZ 85716', 'Tucson', 1);

-- Cottonwood Homes
('Casita in WINE COUNTRY~stargazing and creek', 69, 2, 'The place you wished still existed. In the rare green belt of Arizona. Quiet little, light filled gypsy respite in wine country. Off the beaten path of Sedona yet 25 minutes to the heart of Sedona & Jerome. Grape vines,Apricot, pear,apple trees & blue corn, observing seasons. This is a one room studio, with an open floor plan. there is low traffic and little disruption. The space is cleaned with low toxic cleaners and pest control is used at a minimum. safe. Pet fee $25', 'One room open floor plan. Full kitchen, cafe table with chairs inside and out, an arm chair a writers desk, claw foot tub and large closet...bohemian feel with wild organic gardens you may eat from. Most of the windows have half curtains, as the quality of light is one of the advantages of southwestern living. Shabby chic style bohemian style. Basic kitchen supplies, all organic. We have tested well water and use chemical free detergents and cleaners.', 'Access to garden food,two yoga mats, There is black tea, herbal and medicinal tea, coffee is in the freezer. A small French press and small Japanese coffee bean hand grinder, salt and pepper, olive oil, pots and pans . Blankets , extra sheets, towels. Sarongs for the creek. wi-fi', 'We are happy to answer any questions via text.', 'Please respect check in and out times. We have tested well water and use chemical free detergents and air dry our linens for you. Please compost your food by leaving food in the bucket outside the door or take to bin behind privacy lattice(;', '47 N Farm Circle Rd, Cornville, Arizona', 'Cottonwood', 1);
('Hidden Hills Vineyard Cottage', 137, 3, 'This is an exclusive Vineyard Cottage, centrally located between Sedona and Jerome. Serene, peaceful and rejuvenating atmosphere. Perched on a hilltop of Page Springs overlooking Caduceus Vineyards.', 'The Cottage is cozy but also deluxe overlooking the property Vineyard with the sunset patio steps from the vines. Tastefully furnished and decorated within an entertainment kitchen. Enjoy star gazing with a glass of wine sitting outside in the private outdoors patio. Or a quiet restful afternoon in a comfy setup with a meal of your choice.', 'Guests have access to a complete cottage fully equipped with the premier appliances and kitchenware . Independent entrance and private parking space. Guests have access for a walk through out the Vineyard and a Orchid of the property.  At your arrival we will provide a remote gate control, for you to access in and out the property freely.', 'We live in the property, so personal texts or emails are available. Still guests won''t see us often since we are not on the way and respect privacy boundaries.Interaction with guests are welcome. We give the attention and assistance they will ask for. We can provide suggestions and guidance of any area they will need or require. Restaurants, sightseeings, activities or simple short trips or visits to town.', 'The cottage has a beautiful private bathroom with a washer and dryer. There is a charming living room with a pullout sofa bed. Silvina is licensed dog sitter. She offers dog care on property. If you bring your loyal companion with you let us know in advance to reserve an spot for him/her because there is limited spaces. Ask us for fees and services. It is important to note that during the months of November, December and January the temperature at night can fall to the 30ish. There are 2 AC units in the cottage. One in the kitchen and a second in the bedroom. The temperature in the cottage during the summer months is kept at a pleasant 78 Fahrenheit degrees. We advise to keep the AC at this level during your stay. If the temperature goes under 76 degrees, the unite(s) will freeze-up and damages might produce the system to work irregular with the possibility of interruption the use of the A.C. for the rest of your stay or until it is fixed by a technician. We appreciate you respect this norm.', '1432 N Page Springs Rd, Cornville, Arizona', 'Cottonwood', 1);
('The Ranch House', 99, 5, 'Experience the down home welcome of The Ranch House on a beautiful private horse ranch. Surrounded by the magical mountain regions of Mingus and the Red Rocks of Sedona AZ. The Ranch House sits on a beautiful bluff overlooking the small quaint town of Cottonwood. You can hike right from the The Ranch House into the National Forest. The Ranch House is only a 20 minute drive to Sedona, offering great views, hiking, and site-seeing too. Enjoy beautiful quiet sunsets with a glass of wine.', 'The Ranch House, built in 1962, is part of The Ranch at Trails End, LLC. The original owners were part of the Zalesky family that were prominent ranchers in the Verde Valley. Today the Ranch House is still a horse ranch, we have workshops, retreats and a fabulous space to stay and relax.', 'Guests have access to the Ranch House and grounds. Guest parking is located on the south side of the house. Coming up the driveway, after you have passed the mailboxes, stay to the left and follow the road around, park by the south side door of the house. Please do not disturb the RVs that are on-site. Everyone is welcome to visit the horses, however, you must sign a waiver prior to doing so.', 'The owner, Mary Boles, will be available off and on during the day.', 'There are local residence living in RV''s. Please respect their privacy. After storms, the dirt driveway may be a little more bumpy than normal, what would you expect, living on a ranch.', '1052 S Trail End Dr, Cottonwood, Arizona', 'Cottonwood', 1)
('Cottonwood Old Town Quaint Bungalow', 110, 3, 'This cozy bungalow is the perfect place for visiting medical staff (week long stays) and the perfect place for a weekend get away. Fall weather is perfect for hiking and visiting all that Northern Arizona offers. The proximity of this bungalow to Old Town Cottonwood is so convenient. You can take any side street and end up in Old Town where you will find the local restaurants, wineries, and antique shops. Check out annual events below.', 'The bungalow is the perfect space for your stay in Historic Old Town Cottonwood. The bungalow is quiet (not located on Main Street), comfortable, includes a full kitchen, has a perfect front porch for your breakfast coffee and your evening glass of wine. The bungalow is across the street from the Old Town Center for the Arts, and within walking distance to Old Town restaurants, eateries, and wine tasting rooms.', 'Guest can walk to the 5+blocks of wine tasting rooms, art and clothing shops, and fabulous restaurants.', 'I am always available by text for any questions and needs my guest may have.', 'Use your 30% off Breakfast Coupons at the Old Town Red Rooster Cafe. A good place to begin your visit or to end your visit as you are leaving town. Enjoy a complimentary wine flight at a local tasting room. Coupons will be left on baker''s rack.', '701 N 6th St Cottonwood, Arizona', 'Cottonwood', 1);
('Close 2 Vinyards Sedona Cottonwood Oak Creek', 138, 4, 'The Orchard In Cornville sits at the foot of the original Loy Ranch Homestead. It is a secluded 10 acre property completely fenced with privacy slats running along its north, south, and west sides, while Oak Creek runs the length of the property''s east side.', 'Two Bedrooms, One Bathroom, Kitchen, Washer - Dryer, Office, Pool Table, Ping Pong, Cable TV', 'Feel free to explore the green fields, fruit orchard & private access to Oak Creek for fly fishing, or just cooling off. Enjoy private access to pool, hot tub, outdoor gym, and deck.', 'We more than likely will be away traveling ourselves! During your stay please feel free to contact us anytime day or night with questions.', '@TheOrchardInCornville', '2780 S Candler Dr Cornville, Arizona', 'Cottonwood', 1);

-- Williams homes
('Grand Canyon Straw Bale Retreat', 139, 6, 'This unique straw-bale house is located on 10 acres close to historic Williams, Arizona and the Grand Canyon. Because of the 24" thick straw-bale walls, this home is very cozy and quiet. My home offers a open-floor plan which makes it very spacious with fantastic lighting. Because of the mild northern Arizona temperatures and the highly insulated walls, you will always be comfortable. You will have peace and privacy but will only be a short drive to town.', 'My home is very spacious and quiet. I built it using straw bales (yes actual straw bales!) covered with stucco. This keeps the house cool in summer, warm in winter, quiet, and very fire proof. The home is situated on 10 acres about 11 miles north of Williams, AZ-The gate way to the Grand Canyon. We are about 45 minutes from the Grand Canyon. We are in an excellent location for walking, hiking, and biking. There is a large "Arizona room" (a screened in porch) with a ping-pong table and exercise equipment.', 'Guests have access to the entire house with plenty of parking outside.', 'The Casita Del Rey is a completely separate residence from the main home. Guests get a lot of privacy! Casita Del Rey even has its own "campsite" and picnic area -- hammock ready!', 'Careful: Desert wildlife is abundant! For safety, pets must be watched (a leash is best) while outside. Children should not be left unattended. Earlier this year a mountain lion was spotted on the property. Bobcats and javelina are also very common to the area.', '233 N Grand Canyon Blvd, Williams, AZ 86046', 'Williams', 1);
('Beautiful Cabin in Wooded 4 acre lot.', 165, 6, 'My place is close to National Forest, Hiking Trails, and 2 hours away from Grand Canyon National Park. It is at 7000 ft elevation and only 2.5 hours drive from Phoenix. You’ll love my place because of The cabin is in a 4.3 acre wooded lot adjacent to National Forest and yet only 3 miles from the highway exit.. My place is good for couples, families (with kids), and furry friends (pets). There are plenty of attractions both in Flagstaff and in Williams for tourists and visitors.', 'Bring your own K-Cup pods to make your hot beverage. We have a single server machine with non-diary creamer and sugar available for your convenience. If you are familiar with operating a wood stove, bring logs and enjoy the warmth of burning logs in the wood stove. We are OK for you to bring pets but there will be additional charge for the pets. There is no TV or internet service.', 'This is our vacation home. We don''t live there. But we are available on the phone anytime you have a question.', 'The premises include a pebble-tec swimming pool (unheated) and numerous shaded and unshaded patios. Note: the back-yard area is shared with the owners.', 'Comfort: We aim to please! We have provided two Casita Del Rey robes (these can also be purchased), two sets of towels, pool/swim towels, clean sheets, and 4 pillows. No need to bring your sound machine or a clock radio! However, you might want to bring a camera or binoculars. We have "glamping" items too-a hammock and lantern, grill, charcoal and (hopefully) all the things you may need. Your comfort is important to us as you adventure about in your home away from home!', '805 N Grand Canyon Blvd, Williams, AZ 86046', 'Williams', 1);
('Calley Cottage', 100, 5, 'New Listing! Extraordinary, Ultra-Charming, One-of-a-kind, 4BR Treasure! Central to all Key Attractions!', 'Manistee Hideaway has a great open floor plan allowing our guests to be together or have their space whichever is desired. We also created a fun game \ relaxing room where you will find a Jacuzzi (additional fee) and a shuffle board table for hours of entertainment. Our bedrooms are spacious and quiet from the rest of your group. This home is extremely well constructed using updated fixtures and construction materials to ensure a cozy stay no matter the time of year.', 'You will have access to 100% of the home with the exception of 1 master bedroom closet where we keep all of our additional linens & house supplies for our cleaners. If you decide to add the jacuzzi after a long hike in the Grand Canyon or just to enjoy in addition to your stay then it will be filled and ready for your enjoyment. If the jacuzzi is not something your wanting it will be empty and locked. (turn around stays with the jacuzzi option mean that it will not be up to 102 deg. for your arrival but will be up to temperature for you to enjoy in the late evening of your first stay)', 'If you need anything at all please don''t hesitate to get a hold of us so we can make your stay with us that much more enjoyable and we will do everything we can to accommodate your requests.', 'IF YOU ARE NEEDING MORE SPACE OR HAVE A LARGER PARTY WE OFFER ANOTHER 3 BEDROOM 2 BATH HOUSE NEXT DOOR THAT WILL SLEEP 8 IN BEDS AND 2 MORE ON THE COUCH TOTALING 10. SEARCH FOR THE "SAGINAW HANGOUT" IN AIRBNB TO VIEW.', '440 S 7th St, Williams, AZ 86046', 'Williams', 1);
('Sherwood Forest Cottage', 125, 6, 'Quiet neighborhood tucked in the forest. Listen to the wind in the trees, watch the birds and squirrels and enjoy serenity.', '980 sq. foot 2 story cabin on a 1 acre lot. Linens, towels, pillows and cookware are all in place and available. Pellet stove and baseboard/wall heaters for climate control. Full kitchen with dishwasher. Close to hiking trails, fishing, Bearizona, town of Williams, Flagstaff, Snowbowl, Grand Canyon, Sedona and much more! There is a $50 water fill fee due to the need for hauled water to a cistern at the property. This fee is already included in the cleaning fee section of the listing. A total of $130 for cleaning and water fee.', 'Everything on property is open to guest use, excluding the detached laundry room, boat and trailers.', 'Interaction will be via phone, text or email. Local property manager available if needed.', 'Water is hauled in to underground cistern. Please be conscious of water use. Approximately one week supply.', '1251 Stockmens Rd, Williams, AZ 86046', 'Williams', 1);
('Grand Living Lodge', 255, 3, 'Introductory Special $299. Enchanting, Log-Cabin Lodge, Sleeps 17, Superb Views, Ideal Location!', 'Whether you are here to experience the wonder of the Grand Canyon or a little holiday magic aboard the Polar Express, this brand new home in Williams is perfect for kids young and old. When you enter the front doors you will be transported into a railway car with custom woodwork created by one of the owners, a local artisan carpenter. The decor reflects the long tradition of trains in the Southwest, but this brand new home has all the amenities and comforts you would want in your vacation home. Enjoy the open concept living space with a fully-stocked kitchen, perfect for cooking and enjoying that hot meal after an exciting day of adventures. Sip a cup of coffee or hot cocoa on the covered porch as you watch over the Grand Canyon Railway. With enough space for families, couples and all train aficionados, this home is the perfect place for you. So the next time you are in Williams, let us welcome you aboard our home!', 'Guests will have access to the entire home.', 'I enjoy traveling the world and am not always available - so to help manage my guests and property, I use MyVRHost Vacation Rental Management!', 'Parking is available in the driveway.', '283 S Garland Prairie Rd, Williams, AZ 86046', 'Williams', 1);
